version: 0.2

phases:
  install:
    commands:
      - n 16
      - npm install
  build:
    commands:
      - npm run generate
  post_build:
    commands:
      - aws s3 sync ./dist s3://$S3_BUCKET_WEBPAGE --delete --cache-control max-age=31556952
      - aws s3 cp s3://$S3_BUCKET_WEBPAGE/sw.js s3://$S3_BUCKET_WEBPAGE/sw.js --cache-control max-age=0 --metadata reason=no-cache
      - aws cloudfront create-invalidation --distribution-id $DISTRIBUTION_ID --paths "/*"
